plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.devtools.ksp'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.conect.aplicativoconect'
    compileSdk 35

    defaultConfig {
        vectorDrawables.useSupportLibrary = true
        applicationId "com.conect.aplicativoconect"
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName "1.1"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildFeatures {
        viewBinding true
        dataBinding true
    }

    packaging {
        resources {
            excludes += [
                    'META-INF/DEPENDENCIES',
                    'META-INF/LICENSE',
                    'META-INF/LICENSE.md',
                    'META-INF/LICENSE-notice.md',
                    'META-INF/LICENSE.txt',
                    'META-INF/NOTICE',
                    'META-INF/INDEX.LIST',
                    'META-INF/NOTICE.txt',
                    'META-INF/DEPENDENCIES.txt',
                    'google/**',
            ]
        }
    }
}

configurations.configureEach {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group == 'io.grpc' && details.requested.name == 'grpc-core') {
            details.useVersion '1.48.0'
        }
    }
}

dependencies {
    // Android e Material
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.viewpager2:viewpager2:1.1.0'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'

    // Firebase BoM para gerenciar versões de forma consistente
    implementation platform('com.google.firebase:firebase-bom:33.5.1')
    implementation 'com.google.firebase:firebase-messaging-ktx'
    implementation 'com.google.firebase:firebase-auth-ktx'
    implementation('com.google.firebase:firebase-firestore-ktx') {
        exclude group: 'io.grpc' // Evita duplicação de gRPC
    }
    implementation 'com.google.firebase:firebase-storage-ktx'
    implementation('com.google.firebase:firebase-inappmessaging-display') {
        exclude group: 'io.grpc' // Evita duplicação de gRPC
    }

    // Play Services
    implementation 'com.google.android.gms:play-services-auth:21.2.0'
    implementation 'com.google.android.gms:play-services-location:21.3.0'

    // Navegação
    implementation 'androidx.navigation:navigation-fragment-ktx:2.8.3'
    implementation 'androidx.navigation:navigation-ui-ktx:2.8.3'

    // WorkManager para gerenciamento de tarefas em segundo plano
    implementation 'androidx.work:work-runtime-ktx:2.7.1'

    // Networking e JSON
    implementation 'com.android.volley:volley:1.2.1'
    implementation 'com.squareup.retrofit2:retrofit:2.11.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.11.0'

    // Glide e Firebase UI
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    implementation 'com.firebaseui:firebase-ui-storage:8.0.2'
    implementation 'de.hdodenhof:circleimageview:3.1.0'

    // Firebase Admin SDK e Google Auth para serviços do lado do servidor
    implementation 'com.google.auth:google-auth-library-oauth2-http:1.29.0'

    // Lifecycle
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.8.7'
    implementation 'com.google.android.libraries.places:places:4.1.0'

    // Testes
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'

    // Coroutines para uso com Firebase e WorkManager
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0'
    androidTestImplementation 'org.junit.jupiter:junit-jupiter:5.11.3'

    // gRPC BoM para alinhar as versões do gRPC
    implementation platform('io.grpc:grpc-bom:1.50.1')
    implementation 'io.grpc:grpc-core'
    implementation 'io.grpc:grpc-okhttp'
    implementation 'io.grpc:grpc-stub'
    implementation 'io.grpc:grpc-protobuf-lite'
    implementation 'io.grpc:grpc-android:1.62.2'

    implementation "com.airbnb.android:lottie:5.2.0"


}

apply plugin: 'com.google.gms.google-services'
